 
experimentName: inibitory_STDP_valid
trialConcurrency: 2
maxExperimentDuration: 72h
maxTrialNumber: 1000
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 4
searchSpaceFile: ~/lava_AHPC/nni_experiments/inibitory_STDP_valid/search_space/search_space1.json
useAnnotation: false
tuner: 
    name: Anneal
    classArgs:
      optimize_mode: maximize


trialCodeDirectory: ~/lava_AHPC/nni_experiments/inibitory_STDP_valid/code/
trialCommand: python3 experiment1.py --trial_path inibitory_STDP_valid/
experimentWorkingDirectory: ~/lava_AHPC/nni_experiments/inibitory_STDP_valid/results/
trialGpuNumber: 1


